### ISSUE TITLE
Unable to install on HEAD Rakudo

### ISSUE THREAD

**Issue by japhb** [raku-community-modules/JSON-JWT#5]
Installing (as a dependency) with `zef`, I get:

```
===> Testing: JSON::JWT:ver<1.0>
[JSON::JWT] # Failed test 'Can encode with alg RS256'
[JSON::JWT] # at t/02-encode.t line 18
[JSON::JWT] # Unable to read key
[JSON::JWT] # Failed test 'correct decode succeeds'
[JSON::JWT] # at t/02-encode.t line 20
[JSON::JWT] # Header lists signature type != 'RS256' (HS256)
[JSON::JWT] # You failed 2 tests of 6
===> Testing [FAIL]: JSON::JWT:ver<1.0>
Aborting due to test failure: JSON::JWT:ver<1.0> (use --force-test to override)
```
I'm trying to build against HEAD Rakudo, currently `rakudo-moar-2021.05-2-g4183cdaf3`.  I'm running on Linux Mint 20.1.

I was able to build against the previous commit, `rakudo-moar-2021.05-1-g1962e6744`, approximately a week ago.

**Comment by lizmat** [comment]
Installs without issue for me on MacOS:

````
$ raku --version
Welcome to Rakudo(tm) v2021.05-2-g4183cdaf3.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.05.
$ uname -a
Darwin LizyPro.fritz.box 18.7.0 Darwin Kernel Version 18.7.0: Mon May  3 20:41:19 PDT 2021; root:xnu-4903.278.68~1/RELEASE_X86_64 x86_64
````

**Comment by japhb** [comment]
OK weird, yesterday it failed for me multiple times in a row (I was retrying to make sure it wasn't just flaky), and today it worked first try.  Going to try again before closing this issue to make sure I didn't just get lucky this one time.

**Comment by japhb** [comment]
OK, failed again, this time against `rakudo-moar-2021.05-3-g39e5834dc`.  Flaky test, I'm thinking?

**Comment by lizmat** [comment]
I cannot reproduce, so closing
