### ISSUE TITLE
JSON::JWT Fails to install on 2022-12 Raku via Zef

### ISSUE THREAD

**Issue by jmaslak** [raku-community-modules/JSON-JWT#6]
```[0] ubuntu:~$ zef install JSON::JWT
===> Searching for: JSON::JWT
===> Testing: JSON::JWT:ver<1.1.1>:auth<zef:raku-community-modules>
[JSON::JWT] # Failed test 'correct decode succeeds'
[JSON::JWT] # at t/01-decode.rakutest line 12
[JSON::JWT] # Too many positionals passed; expected 0 arguments but got 3
[JSON::JWT] # Failed test 'Got correct data'
[JSON::JWT] # at t/01-decode.rakutest line 14
[JSON::JWT] # expected: '1234567890'
[JSON::JWT] #      got: (Any)
[JSON::JWT] # You failed 2 tests of 7
[JSON::JWT] # Failed test 'Can encode with alg HS256'
[JSON::JWT] # at t/02-encode.rakutest line 12
[JSON::JWT] # Too many positionals passed; expected 0 arguments but got 3
[JSON::JWT] Header lists signature type != 'HS256' (none)
[JSON::JWT]   in method decode at /tmp/.zef/414a64b9e477612436ed5a5b3096765eb5c0d665.tar.gz/JSON-JWT-1.1.1/lib/JSON/JWT.rakumod (JSON::JWT) line 19
[JSON::JWT]   in block <unit> at t/02-encode.rakutest line 14
[JSON::JWT] # You planned 6 tests, but ran 3
[JSON::JWT] # You failed 1 test of 3
===> Testing [FAIL]: JSON::JWT:ver<1.1.1>:auth<zef:raku-community-modules>
Aborting due to test failure: JSON::JWT:ver<1.1.1>:auth<zef:raku-community-modules> (use --force-test to override)
[1] ubuntu:~$```

**Comment by 2colours** [comment]
Things are getting interesting: with Ubuntu 20.04 as a WSL instance, it worked; with Ubuntu 20.04 on a standalone system, I could reproduce the issue.

**Comment by 2colours** [comment]
Okay, I think I see the difference now...
It's the [Digest module](https://github.com/grondilu/libdigest-raku) that exposed a `Digest::HMAC` package recently, hence effectively hijacking old modules' `use Digest::HMAC`.

~~Not gonna lie, it's a shame that zef is perfectly content with installing `Digest` when someone asks for `Digest::HMAC` specifically; moreover `Digest` can even beat `Digest::HMAC` by recency.~~
Edit: it's not so simple: `Digest::HMAC` itself depends on `Digest`, and then fails to find itself while testing, therefore you end up with `Digest` installed and `Digest::HMAC` skipped, which means you do have a `Digest::HMAC` entry but it's the wrong one...

A solution is to refine the dependency of this module - unfortunately, that won't fix 20 other modules still.

**Comment by lizmat** [comment]
I think this is now fixed, please re-open if not
